apiVersion: v1
kind: Secret
metadata:
  name: seller-secret
  namespace: cartcraft
type: Opaque
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "seller_db"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/seller_db"