apiVersion: v1
kind: Secret
metadata:
  name: pricing-secret
  namespace: cartcraft
type: Opaque
data:
  DB_HOST: "cG9zdGdyZXM="
  DB_PORT: "NTQzMg=="
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  DB_NAME: "cHJpY2luZ19kYg=="
  LANGSMITH_API_KEY: "bHN2Ml9wdF9mMWI0OWVhYTExMDQ0MzY5OGQ2MDU2Yjk2YjhmNWEwZl83MTVhOGE0NDA5"
  GEMINI_API_KEY: "QUl6YVN5REZUOW4wUmRrWDJnMFR0MkEybW9NTUhaemNXUlh6NnR3"
