"""initial pricing schema

Revision ID: 715b6bb1649e
Revises: 
Create Date: 2026-02-20 01:39:24.693441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '715b6bb1649e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_evaluation_batch',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_variants', sa.Integer(), nullable=True),
    sa.Column('processed_variants', sa.Integer(), nullable=True),
    sa.Column('proposals_created', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_evaluation_batch_id'), 'pricing_evaluation_batch', ['id'], unique=False)
    op.create_table('pricing_memory',
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('last_strategy', sa.Enum('RAISE', 'LOWER', 'HOLD', name='strategytype'), nullable=True),
    sa.Column('last_market_state', sa.String(), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_price_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oscillation_score', sa.Integer(), nullable=True),
    sa.Column('stability_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_pricing_memory_variant_id'), 'pricing_memory', ['variant_id'], unique=False)
    op.create_table('pricing_metrics_snapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pricing_evaluation_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_metrics_snapshot_id'), 'pricing_metrics_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_metrics_snapshot_variant_id'), 'pricing_metrics_snapshot', ['variant_id'], unique=False)
    op.create_table('pricing_price_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['pricing_evaluation_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_price_history_id'), 'pricing_price_history', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_price_history_variant_id'), 'pricing_price_history', ['variant_id'], unique=False)
    op.create_table('pricing_ai_stage1_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('metrics_snapshot_id', sa.String(), nullable=True),
    sa.Column('market_state', sa.String(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pricing_evaluation_batch.id'], ),
    sa.ForeignKeyConstraint(['metrics_snapshot_id'], ['pricing_metrics_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_ai_stage1_log_id'), 'pricing_ai_stage1_log', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_ai_stage1_log_variant_id'), 'pricing_ai_stage1_log', ['variant_id'], unique=False)
    op.create_table('pricing_ai_stage2_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('stage1_log_id', sa.String(), nullable=True),
    sa.Column('strategy', sa.Enum('RAISE', 'LOWER', 'HOLD', name='strategytype'), nullable=False),
    sa.Column('aggressiveness', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['pricing_evaluation_batch.id'], ),
    sa.ForeignKeyConstraint(['stage1_log_id'], ['pricing_ai_stage1_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_ai_stage2_log_id'), 'pricing_ai_stage2_log', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_ai_stage2_log_variant_id'), 'pricing_ai_stage2_log', ['variant_id'], unique=False)
    op.create_table('pricing_proposal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=True),
    sa.Column('metrics_snapshot_id', sa.String(), nullable=True),
    sa.Column('ai_decision_id', sa.String(), nullable=True),
    sa.Column('memory_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['pricing_ai_stage2_log.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['pricing_evaluation_batch.id'], ),
    sa.ForeignKeyConstraint(['metrics_snapshot_id'], ['pricing_metrics_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_proposal_id'), 'pricing_proposal', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_proposal_variant_id'), 'pricing_proposal', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_proposal_variant_id'), table_name='pricing_proposal')
    op.drop_index(op.f('ix_pricing_proposal_id'), table_name='pricing_proposal')
    op.drop_table('pricing_proposal')
    op.drop_index(op.f('ix_pricing_ai_stage2_log_variant_id'), table_name='pricing_ai_stage2_log')
    op.drop_index(op.f('ix_pricing_ai_stage2_log_id'), table_name='pricing_ai_stage2_log')
    op.drop_table('pricing_ai_stage2_log')
    op.drop_index(op.f('ix_pricing_ai_stage1_log_variant_id'), table_name='pricing_ai_stage1_log')
    op.drop_index(op.f('ix_pricing_ai_stage1_log_id'), table_name='pricing_ai_stage1_log')
    op.drop_table('pricing_ai_stage1_log')
    op.drop_index(op.f('ix_pricing_price_history_variant_id'), table_name='pricing_price_history')
    op.drop_index(op.f('ix_pricing_price_history_id'), table_name='pricing_price_history')
    op.drop_table('pricing_price_history')
    op.drop_index(op.f('ix_pricing_metrics_snapshot_variant_id'), table_name='pricing_metrics_snapshot')
    op.drop_index(op.f('ix_pricing_metrics_snapshot_id'), table_name='pricing_metrics_snapshot')
    op.drop_table('pricing_metrics_snapshot')
    op.drop_index(op.f('ix_pricing_memory_variant_id'), table_name='pricing_memory')
    op.drop_table('pricing_memory')
    op.drop_index(op.f('ix_pricing_evaluation_batch_id'), table_name='pricing_evaluation_batch')
    op.drop_table('pricing_evaluation_batch')
    # ### end Alembic commands ###
