apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  namespace: cartcraft
spec:
  serviceName: meilisearch
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.6
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: meili-storage
              mountPath: /meili_data
  volumeClaimTemplates:
    - metadata:
        name: meili-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: cartcraft
spec:
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
  type: ClusterIP
