apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-config
  namespace: cartcraft
data:
  PORT: "4007"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_HOST: "kafka"
  KAFKA_PORT: "9092"
  LANGSMITH_TRACING: "true"
  LANGSMITH_ENDPOINT: "https://eu.api.smith.langchain.com"
  LANGSMITH_PROJECT: "cartcraft"
