apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: cartcraft-ingress
  namespace: cartcraft

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:

          - path: /buyer
            pathType: Prefix
            backend:
              service:
                name: cc-buyer-service
                port:
                  number: 5000

          - path: /seller
            pathType: Prefix
            backend:
              service:
                name: cc-seller-service
                port:
                  number: 5000

          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: cc-admin-service
                port:
                  number: 5000

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000