apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: cartcraft-ingress
  namespace: cartcraft

spec:
  rules:

    - host: seller.cartcraftio.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seller-frontend-service
                port:
                  number: 80

    - host: admin.cartcraftio.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend-service
                port:
                  number: 80

    - host: cartcraftio.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: buyer-frontend-service
                port:
                  number: 80

    - host: api.cartcraftio.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000