apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricingservice
  namespace: cartcraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricingservice
  template:
    metadata:
      labels:
        app: pricingservice
    spec:
      containers:
        - name: pricingservice
          image: bhuvan0fficial/cartcraft-pricingservice:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 4008

          envFrom:
            - configMapRef:
                name: pricing-config
            - secretRef:
                name: pricing-secret

          readinessProbe:
            httpGet:
              path: /
              port: 4008
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 4008
            initialDelaySeconds: 50
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"