apiVersion: v1
kind: Secret
metadata:
  name: pricing-secret
  namespace: cartcraft
type: Opaque
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "pricing_db"
  LANGSMITH_API_KEY: "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"
  GEMINI_API_KEY: "AIzaSyDFT9n0RdkX2g0Tt2A2moMMHZzcWRXz6tw"