apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: cartcraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: bhuvan0fficial/cartcraft-authservice:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 4001 

          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 50
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"