apiVersion: v1
kind: Service
metadata:
  name: communicationservice
  namespace: cartcraft
spec:
  selector:
    app: communicationservice
  ports:
    - port: 4003
      targetPort: 4003
  type: ClusterIP