apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
  namespace: cartcraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: bhuvan0fficial/cartcraft-productservice:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 4003

          envFrom:
            - configMapRef:
                name: product-config
            - secretRef:
                name: product-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4003
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4003
            initialDelaySeconds: 40
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
