apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellerservice
  namespace: cartcraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sellerservice
  template:
    metadata:
      labels:
        app: sellerservice
    spec:
      containers:
        - name: sellerservice
          image: bhuvan0fficial/cartcraft-sellerservice:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 4005

          envFrom:
            - configMapRef:
                name: seller-config
            - secretRef:
                name: seller-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4005
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 4005
            initialDelaySeconds: 50
            periodSeconds: 20

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
