apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: cartcraft
data:
  PORT: "4000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://authservice:4001"
  BUYER_SERVICE_URL: "http://buyerservice:4002"
  PRODUCT_SERVICE_URL: "http://productservice:4003"
  ORDER_SERVICE_URL: "http://orderservice:4004"
  SELLER_SERVICE_URL: "http://sellerservice:4005"
  SEARCH_SERVICE_URL: "http://searchingservice:4006"
  PRICING_SERVICE_URL: "http://pricingservice:4007"
  COMMUNICATION_SERVICE_URL: "http://communicationservice:4008"