apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: cartcraft
type: Opaque
stringData:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "product_db"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/product_db"