name: Backend CI

on:
  push:
    branches:
      - backend-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: ls -la